name: Terraform Deployment
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v4

      - name: Fetch Keys from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: http://100.31.212.13:8200
          role: gh-actions-role
          method: jwt
          secrets: |
            aws/creds/terraform-role access_key | AWS_ACCESS_KEY_ID ;
            aws/creds/terraform-role secret_key | AWS_SECRET_ACCESS_KEY ;
            aws/creds/terraform-role security_token | AWS_SESSION_TOKEN

      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve